apiVersion: v1
kind: Service
metadata:
  name: protonema-service
  labels:
    app: protonema
spec:
  type: NodePort
  selector:
    app: protonema
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: trxman
      port: 2333
      targetPort: 2333
      nodePort: 32333
    - name: srv
      port: 9991
      targetPort: 9991
      nodePort: 30991
