# Quarkus Application Configuration
quarkus.application.name=protonema
quarkus.http.port=8080

# Database Configuration (H2 In-Memory)
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:h2:mem:protonemadb;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=false

# Protonema ISO8583 Configuration
protonema.server.trxman.port=2333
protonema.server.trxman.min-sessions=10
protonema.server.trxman.max-sessions=20

protonema.server.srv.port=9991
protonema.server.srv.min-sessions=1
protonema.server.srv.max-sessions=150

protonema.biller.host=localhost
protonema.biller.port=2300
protonema.biller.space=tspace:biller

protonema.echo.enabled=true
protonema.echo.interval=60s
